### ISSUE TITLE
Add data to "Gana Control" profile

### ISSUE THREAD

**Issue by Ganacontrol** [acceptbitcoincash/acceptbitcoincash#1000]
Please add Twitter profile @ganacontrol to the Gana Control profile in acceptbitcoin.cash
---------------
- name: Gana Control
  url: https://ganacontrol.com/
  twitter: ganacontrol
  bch: yes
  btc: yes
  othercrypto: no
eu | Europe

**Comment by kenman345** [comment]
what section is this in?
