### ISSUE TITLE
Can not add Norwegian language tag

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1011]
I can not add `lang: no` to the listing in #1003 because then `bundle exec rake` complains:

```
C:/Ruby24-x64/bin/ruby.exe ./verify.rb
  1. _data/health.yml:Barbershop.no: 'false': not a string.
```

**Comment by kenman345** [comment]
yaml changes things to booleans when its a yes or no

the additions request form handles this by using explicit type.

`country: !!str NO`

**Comment by EchterAgo** [comment]
Great, thanks!

**Comment by EchterAgo** [comment]
Hrmm, I still get
```
1. _data/health.yml:Barbershop.no: 'false': not a string.
```

when I add `lang: !!str no` to the Barbershop.no listing.

**Comment by kenman345** [comment]
```yml
  lang: 'no'
```
seems to work. sorry about that

**Comment by EchterAgo** [comment]
Working now, thanks!
