### ISSUE TITLE
Porn site accepting BCH (https://www.wifebucket.com/)

### ISSUE THREAD

**Issue by xskl0** [acceptbitcoincash/acceptbitcoincash#1023]
---------------

- name: WifeBucket
  url: https://www.wifebucket.com/
  img: I dont know how to copy the logo shown as a "favicon"
  twitter: 
  facebook: 
  region: 
  country: 
  city: 
  bch: YES
  btc: YES
  othercrypto: YES
  doc: 
```

**Comment by billyboyluis** [comment]
Can't stand porn sites really but accepting over 400 coins is huge risk taker. 
I wonder why there is no twitter account, is there no-one working in an office? 

Have no tried it though as I won't risk my wife's scorn for a test.

**Comment by xskl0** [comment]
Discard this one but two of the porn sites I submited are using Bitpay. These should be added
