### ISSUE TITLE
Offline Help

### ISSUE THREAD

**Issue by seamarhay** [acceptbitcoincash/acceptbitcoincash#1070]
I was on the Bitcoin Cash Fund Submit a Proposal Page. It leads to this (I did not allow consensusbot - as I have no idea what it is). Anyhow, looking for a way to start a new project. I would like to present an opportunity, but not sure if it should be an ISSUE here. Any suggestions. This is primarily an offline suggestion/proposal.

**Comment by kenman345** [comment]
We are not associated with the BCF but applaud their efforts and many of our team help them out separately but not directly as Bitcoin Cash initiative team members. 

I would suggest you go back to the original repository you started at or go to the bitcoin cash fund discord channel, you will find many interested folks there that would love to hear about project proposals.

When you have a site though, let us know you accept BCH on it and we’ll get you listed
