### ISSUE TITLE
Coins.ph does not support Bitcoin Cash

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#110]
Coins.ph and coins.co.th do not support Bitcoin Cash. They only thing they did was dump all the BCC and credit the resulting BTC to their customers. Not exactly what I would call supporting it.

**Comment by kenman345** [comment]
I cannot find Coin.co.th....

**Comment by EchterAgo** [comment]
It is basically the same company, just their Thai website

**Comment by kenman345** [comment]
I was meaning, Is it listed or not?

**Comment by EchterAgo** [comment]
No, it wasn't listed

**Comment by maemon** [comment]
wait i though they made a public statement about supporting BitcoinCash?

**Comment by kenman345** [comment]
If you can link me, I can adjust appropriately. I was unable to find anything
this is the latest I can find on them talking about Bitcoin Cash: https://coins.ph/blog/bitcoin-cash-update/

**Comment by EchterAgo** [comment]
I use the service, they do not have BCC. They did convert them to BTC and
credited their users. From the link you provided:

"After careful consideration, we have decided to convert the BCC created
during the fork to BTC, and credit the corresponding amount of BTC to
customers who held BTC in their Coins.ph wallet at the time of block
478,558 (August 1st 9:16 pm Philippines time, the time the fork occurred)."
