### ISSUE TITLE
Satoshidice & Luckygames supports bitcoincash

### ISSUE THREAD

**Issue by maemon** [acceptbitcoincash/acceptbitcoincash#112]
Hey gambling sites, Satoshidice (https://satoshidice.com/) and Luckygames (https://luckygames.io) both support bitcoincash.

Can you please add an extra category for betting or gambling and add these 2 sites.

Thank you!

**Comment by kenman345** [comment]
They can@ If you want to help then I need 32x32 png formatted icons for each. I plan to add a Gambling section later today at least in our code base so that we can push that out in our next deployment

**Comment by maemon** [comment]
Alright, I've attached a 32x32 png logo for satoshidice
![saotshidice](https://user-images.githubusercontent.com/20421616/30865013-9d0dd85a-a2ff-11e7-8e63-10ab37796500.png)

**Comment by kenman345** [comment]
@zquestz @mohrt @t0p0lin0 know of any other sites to take a look at for the gambling section?
