### ISSUE TITLE
Create a site-specific logo for AB.C

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#116]
Ideas:

- the "O" in Bitcoin can be the coin itself, with the 'cradle' below it
- the 'cradle' can be centered above the 'AcceptBitcoin.Cash' text
- the 'AcceptBitcoin.Cash' text can be split up from it's "URL format" and stacked vertically

**Comment by rawb0t** [comment]
@t0p0lin0 do we still need this?

**Comment by t0p0lin0** [comment]
@rawb0t -- leave it for now, as I had made some minor modifications to the logo, but haven't sent them anywhere yet. I will handle that, then close this issue once done. Thanks for the reminder in that sense tho!

**Comment by t0p0lin0** [comment]
Closing, as we're going with this for the near future:

![image](https://user-images.githubusercontent.com/31756199/34194724-1ea808e4-e528-11e7-9efd-2b9e6e91a1b2.png)
