### ISSUE TITLE
Replace the "broken" image file used when a listing doesn't have an image with something else

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1187]
When a listing does not have an image file an icon that seems to imply a broken image is used. When I see this it always makes me wonder if there is a problem with my internet connection or the website on first sight. It takes me a few milliseconds to remember that it means "no image" instead of "broken image", even though I work on the site regularly. Other users might not even realize that this does mean no image. We should consider replacing that with either a better symbol or even omitting the image circle completely for these listings.

**Comment by EchterAgo** [comment]
Another issue is that the icon used is an exact copy of the icon that Internet Explorer used to indicate a broken image, so there might be licensing problems with this.

**Comment by EchterAgo** [comment]
I would prefer omitting the circle and not displaying anything there.

**Comment by EchterAgo** [comment]
Adding `style="visibility: hidden;"` to the img tag where we have no image hides it without messing with the layout. I think an empty image would be better than what we have now, but it might also be seen as problems with the connection or the site. I'll check if I can come up with a symbol.

**Comment by EchterAgo** [comment]
Maybe something like this would work: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCeF2uQzXx4W9agnCd5caOiBGM3QxH9QLIrqJB14LlGhb-Xu08

**Comment by EchterAgo** [comment]
![noimage](https://user-images.githubusercontent.com/922233/43902561-9bbc6da4-9c14-11e8-85f6-5800d7015ae6.png)
![noimage2](https://user-images.githubusercontent.com/922233/43902562-9c230b2c-9c14-11e8-98f0-1550464893b7.png)

One of these might also work.

**Comment by EchterAgo** [comment]
@chaintip 100 days

**Comment by chaintip** [comment]
`0.01029365 BCH`| `~   5.02 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld42kv3ngw66szpec4xxjfkqpjfq7sswl73qfu) to this issue by @EchterAgo.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/46), get a pull request merged with ```@chaintip fixes #1187``` in the creation comment.
