### ISSUE TITLE
Add BitcoinLogo.eu merchant assets

### ISSUE THREAD

**Issue by BigBlockIfTrue** [acceptbitcoincash/acceptbitcoincash#126]
Please add my merchant graphics site! It is properly usable now and has SVG, PNG and PDF downloads for all files.

**BitcoinLogo.eu**
by BigBlockIfTrue
https://bitcoinlogo.eu

I am still planning on adding text and colour customisation options in the future (e.g. localisation, green colour fans).

**Comment by t0p0lin0** [comment]
In progress, should be added soon. Thanks, and wonderful work on these!

**Comment by t0p0lin0** [comment]
Completed!
