### ISSUE TITLE
Add a new section for sites listing where you can spend Bitcoin Cash?

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1264]
As said in #1262. There are a few already:

- [Marco Coino](https://marcocoino.bitcoin.com/)
- [Bitcoin People Online](https://bitcoinpeople.online/) (#1170)
- [The Real Bitcoin Club](https://map.therealbitcoin.club/) (#1224)
- [greenpages.cash](https://greenpages.cash/)

I think it would be a good idea to create a new category for these and link them here.

**Comment by kenman345** [comment]
I would say if anything it would be a new page, likely called "directories". We can discuss this later, not a focus right now on this day.

**Comment by EchterAgo** [comment]
https://www.megastock.com/ directory of WebMoney vendors

**Comment by EchterAgo** [comment]
https://www.satoshiware.com/bitcoin-cash-accepted-here

**Comment by EchterAgo** [comment]
https://cryptwerk.com/pay-with/bch/

**Comment by EchterAgo** [comment]
http://freestatebitcoin.com/tour/

see #1360

**Comment by EchterAgo** [comment]
https://elipay.com/locations

**Comment by EchterAgo** [comment]
As we have so many of these now, I'm going to go ahead and just create a category for them.

**Comment by kenman345** [comment]
Yea go for it

**Comment by EchterAgo** [comment]
I want to call it something like "Other Directories" and I think `sitemap` would be a good symbol:

![image](https://user-images.githubusercontent.com/922233/56181712-ea7ce700-6038-11e9-8634-2512684e3b9f.png)

**Comment by EchterAgo** [comment]
Oh, we use `sitemap` for hosting already :\

**Comment by EchterAgo** [comment]
`list` seems to be a good fit and we don't use it yet.

**Comment by EchterAgo** [comment]
Seems that therealbitcoin.club is dead and the guy switched to DASH:

https://www.reddit.com/r/dashpay/comments/9c5srf/today_we_donated_1_dash_to_a_stranger_working_in/e58798d/?context=3

Looks like another casualty of the "hash war".

**Comment by EchterAgo** [comment]
Looking good: ![image](https://user-images.githubusercontent.com/922233/56183174-8b6ea080-603f-11e9-93d1-cd2bd8d74ee2.png)

**Comment by EchterAgo** [comment]
Oh no, I forgot to list https://acceptbitcoin.cash/ !
