### ISSUE TITLE
Move Tutanota from "software" to "email" category

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1279]
As title says, Tutanota is much more accurately described as an email service than a software service - please fix!

**Comment by EchterAgo** [comment]
They are listed under Email already (switch off "Only show merchants accepting Bitcoin Cash" to see it). They do not accept any cryptocurrency for payments yet. They only acccept donations so the listing under software donations is the best category fit we have now. They are definitely not archives, education, human needs or non-profit. It likely would fit better into a services category under donations, but we don't have enough listings to justify creating such a category. We will certainly list them under email as soon as they start accepting cryptocurrencies.
