### ISSUE TITLE
Adult section 

### ISSUE THREAD

**Issue by LovelyCorrine** [acceptbitcoincash/acceptbitcoincash#131]
A separate section for Adult services so they don't get lumped in with Other

**Comment by kenman345** [comment]
Already in the works. We have the section created. we just want to make sure it has a disclaimer before searching through it.

**Comment by kenman345** [comment]
I see you're also a site. Are you asking to be included in that list when we add that section to the live site? If so, please provide any ifnromation you can such as do you accept Bitcoin? Bitcoin Cash? OTher Crypto? Twitter account? 

Do you have any restrictions using Bitcoin Cash? Such as only available as a payment option if you buy a certain price plan or higher?

**Comment by LovelyCorrine** [comment]
I am a site but it was suggested that I request an adult section for it to be submitted to. If people want to have the ability to avoid adult content it's probably best for it to have its own space. If you are happy for it to go in an existing category I'll list my site request as to the requirements, just trying to be respectful

**Comment by kenman345** [comment]
Give us the info, we will add it to what we have. We are just not exposing that part of the site until we make sure it isnt accidentally clicked while people are at work. We need to add to include NSFW sites when searching and potentially a click through when you click on adult sites to confirm they are over 18. This is in the works, just may take a few days.

**Comment by LovelyCorrine** [comment]
Cool, I don't know of any adult sites that don't have their own age gate but I understand.
Thanks

Any crypto listed with coinomi/shapeshift
Coins other than btc only for deposits and in person payments, not online sessions yet. 
Twitter @lovelycorrine
  - name: Lovely Corrine - independent escort
    url: https://www.thelovelycorrine.com
    img: site.png
    bcc: Yes
    btc: Yes
    othercrypto: Yes
    doc: https://www.thelovelycorrine.com/bitcoin-and-other-cryptocurrencies/
https://www.thelovelycorrine.com/booking-info/

**Comment by kenman345** [comment]
Hi Corrine, 

While lovely (had to make a pun), we feel that listing your site and services will not be in the interest of the site. It is no secret that cryptocurrency can be used for services like yours but the ease and access the site provides to request merchants to accept Bitcoin Cash payments does not make sense for what you do/offer. We are not a classified listing or the end all be all of the internets Bitcoin Cash acceptance.  We hope you can find other places to list your services and wish you well.

This issue will now be closed. Thank you for your interest. If you were offering videos and pictures being a paywall that accepted Bitcoin Cash this would be a different story but as it stands now, our decision has been made.
