### ISSUE TITLE
Thank you @gitcash_testtip! `0.01505987 BCH`| `~   8.10 USD` has now been tipped to this issue.

### ISSUE THREAD

**Issue by thecoklat** [acceptbitcoincash/acceptbitcoincash#1310]
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/45), get a pull request merged with ```@chaintip fixes #1260``` in the creation comment.

_Originally posted by @chaintip in https://github.com/acceptbitcoincash/acceptbitcoincash/issues/1260#issuecomment-425430486_

**Comment by EchterAgo** [comment]
What are you trying to do here?
