### ISSUE TITLE
Discussion: Add Frostwire?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#132]
So, Forstwire accepts BCC for donations. They do not have a paid product. 

If I am not wrong, Wikipedia is listed on our site in 'Other' but also does not have a product, just accepts BTC as donations. I am wondering if we should make a Donate or Charity section, but with a completely different tweet. One asking to accept Bitcoin Cash for donations not payments. Maybe we add a tag to the new yml that indicates donation but when missing is assumed 'payment' so the wording will be the same besides that word?

I think it might be nice to add this, or at least consider this as an option.

**Comment by kenman345** [comment]
Pinging @deadr0ck @rawb0t @jrkong @t0p0lin0 @zquestz

**Comment by rawb0t** [comment]
They're still supported by BCC and therefore support BCC. I think they should be added. I don't think we should add a new section for it, however. Just put it wherever it's most relevant. I also don't much see the value in tagging it specifically as donations.

**Comment by kenman345** [comment]
okay, Maybe we put it in "other" but again, I feel like it might be nice to list Red Cross and other charities and services that are free but accept crypto donations. We can always do that in the ffuture though

**Comment by rawb0t** [comment]
I'm not against adding charities but frostwire isn't a charity. it's a torrent client. it should go wherever we'd throw torrent clients

**Comment by jrkong** [comment]
I think we should make a donations category and a torrents category. For situations like this though can we mark them with a warning like with Keepkey where we mention they only offer Bitcoin Cash donation method?

**Comment by kenman345** [comment]
Keepkey only offers BCC donation but not for purchases?

I think adding a torrent section might be nice but for now I can add it to the 'Other' category and I will update Wikipedia and Frostwire to include an exception stating they do not have paid accounts but accept donations.

**Comment by jrkong** [comment]
No but we have a warning for it that says the wallet is still in beta, I was thinking we could use the same mechanic to warn people that they only accept donations.
