### ISSUE TITLE
New website accepting Bitcoin Cash

### ISSUE THREAD

**Issue by woollymasters** [acceptbitcoincash/acceptbitcoincash#133]
websites:
  - name: GiftOff
    url: https://www.giftoff.com/
    img: giftoff.png
    bcc: Yes
    btc: Yes
    othercrypto: Yes

**Comment by kenman345** [comment]
Says BCC yes but the page doesnt say that anywhere. Are you needing to follow any special instructions to use BCC or is it a payment option at the end but does not get shown on the main page?

**Comment by woollymasters** [comment]
Hi thanks for getting back, sorry I am not a programmer, just trying to add
this site as I found you guys on reddit. So yes it is a payment option at
the end. I have used them over the years, and are very good.
