### ISSUE TITLE
Some listings to add

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1427]
Anyone who has some time, feel free to add listings from these:

- [x] https://www.sens.org/donate
- [x] https://stake.com/
- [x] https://www.reddit.com/r/btc/comments/9ml8ee/stakecom_the_most_popular_crypto_casino_now/
- [x] https://wallet.advcash.com/index_page | bch btc oth | payments
- [x] https://cryptopay.me/ | btc oth | payments
- [x] https://www.bitnovo.com/ | bch btc oth | payments
- [x] https://paybis.com/ | btc bch oth | exchange
- [x] https://www.hotfilepremiumstore.com/ | bch btc bitpay webmoney | cryptoservice
- [x] https://keyinstant.com/ | bch btc oth bitpay coingate webmoney | cryptoservice
- [x] http://digitalkeys.biz/ | bch btc oth coinify | cryptoservice
- [x] https://multi-vpn.biz/ | bch btc oth coinpayments.net | security
- [x] https://bytesized-hosting.com/ | bch btc oth coinpayments.net | hosting
- [x] https://cleverhost.ca/ | bch btc oth coinpayments.net | hosting
- [x] https://www.centerserv.com/ | bch btc oth coingate | hosting
- [x] https://koddos.net/ | btc oth coinpayments.net | hosting
- [x] https://lacicloud.net/ | btc oth coinpayments.net | cloud 2019-03-05 broken site
- [x] https://betpools.cash/ | 2019-03-05 down
- [x] https://ramen.chopsticks.cash/ | obsolete / ot
- [x] https://cyberianmine.de/team/
- [x] https://pushtx.btc.com/ | 2019-03-05 Internal error
- [x] Pandacash developed a one-click SDK for BCH, deservingly winning Devcon
- [x] https://www.e-vpn.co.uk/client/cart.php?a=checkout | bch oth | security 2019-03-05 out of stock https://www.reddit.com/r/btc/comments/9uwzr9/ordering_a_vpn_service_and_found_it_accepts/
- [x] veracrypt donations
- [x] https://www.eevblog.com/crypto-currency/ | bch btc oth | donations
- [x] https://www.freevoipdeal.com/ | btc bch bitpay | communication
- [x] http://www.fleurmaison.co.uk/ | bch btc oth coingate | flowers
- [x] https://swissmade.host/en/blog/New-Payment-Method-Reduced-Colocation-Fees | bch | hosting
- [x] https://ravishdesigns.com.au/ | btc | jewelry
- [x] http://www.cryptoaccountant.pro/ | bch btc oth | service accountant
- [x] https://www.esportsinvaders.com/ | bch btc bitpay | gaming/retail | 2019-05-03 down
- [x] http://oddevenbets.com/ | btc | gambling
- [x] https://topbet.eu/ | gambling

**Comment by kenman345** [comment]
I added checkboxes to your comment and marking off ones I open PRs for

**Comment by kenman345** [comment]
or that are already on the site

**Comment by kenman345** [comment]
Not sure what category  https://ramen.chopsticks.cash/ would fit or what its used for

**Comment by kenman345** [comment]
we've seen discoverdash before and i dont think it belongs as a listing on our site

**Comment by EchterAgo** [comment]
Discoverdash ended up on the list by accident, I used that to find some of the listings on the list.

**Comment by EchterAgo** [comment]
@kenman345 should I put credit card providers in the banking category?
