### ISSUE TITLE
Retail: 1stboards electric skateboards

### ISSUE THREAD

**Issue by inktech** [acceptbitcoincash/acceptbitcoincash#143]
Hi, 
  We are 1stboards.com and 1stboards.world , and we accept bitcoin and bitcoin cash. We would like to be added to acceptbitcoin.cash website directory

**Comment by kenman345** [comment]
Thats cool. So we need just one or two things. 1, do you have a facebook or twitter presence? We would like to include that information not to request that you accept bitcoin cash but for potential other integrations we are planning as well as data completeness.

Do you have a square logo we can use in the listing? 
Also, I added something to my cart and tried to checkout. It only says about payment from Bitcoin, will users wishing to use Bitcoin Cash need to know anything special to be able to pay in Bitcoin Cash? Do you have instructions if this is the case?

**Comment by kenman345** [comment]
Can you @inktech provide a square logo to use on the site? the favicon they have is in a language I cannot understand. I do not wish to misrepresent the site by using something wrong.

**Comment by rawb0t** [comment]
closing due to @inktech's lack of response here and due to the fact that during a checkout process I was unable to find any option to pay with Bitcoin Cash (only Bitcoin Legacy)
