### ISSUE TITLE
Handle Bitcoin SV listings

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1431]
Our options are

1. Remove them
2. Flip them to `othercrypto`
3. Add `bsv` status

Personally I prefer option 2. Here is a list of services I know will use BSV, haven't checked that all of them are listed:

- handcash
- moneybutton
- yours
- cryptografitti
- cryptonize.it
- https://bitek.co/

**Comment by kenman345** [comment]
The bot already can aid in updating the current tags to handle Option 2 easily. I think we shouldn't remove anything that is still a business, though I know listings like Coinmix.to decided not to continue at all so I removed them as a listing entirely.

Adding a `BSV` flag is fine but I would want to script something to update all the listings to be false at first and then update accordingly if we were to go down that path. I also have no plans to update the UI to reflect that so its kind of grouped with `othercrypto` anyways.

**Comment by EchterAgo** [comment]
Oh, right, forgot about coinmix. There were a few more listings by NxtChg, all of them listed here:

https://www.reddit.com/r/btc/comments/9my15p/psa_if_ctor_is_implemented_in_november_i_will_be/

**Comment by kenman345** [comment]
going to be so hard to identify some of these. Centbee says bitcoin cash.....so its going to be hard to say we caught all of them. I can update the logic for the site to consider BSV tag as part of the othercrypto for generating the JSON and the UI. So if either of those tags (`bsv` and `othercrypto`) are set to true, it would count it. If we go that path that is.

**Comment by EchterAgo** [comment]
They have all announced it, but some are still using Bitcoin Cash / BCH all over their site, even MoneyButton or their "Dragons Den" bchclub.org. I think we should wait a bit until these businesses actually change, the list is just for reference and checking in the future. Wouldn't surprise me if some of them don't go through with it.

**Comment by EchterAgo** [comment]
Keys4coints accepts both

https://www.reddit.com/r/btc/comments/a1skb4/coinswap_keys4coins_review/

**Comment by EchterAgo** [comment]
- Moneybutton has removed all other options to add money except BSV
- Yours.org is still broken, waiting for it to work again to see how they handle it
- Cryptonize.it still says accepting BCH but the price seems to be the price of BCH + BSV
- Cryptoshoppe announced switching to BSV, but the site is currently down

#1442 updates to what I have currently confirmed. Still waiting for yours and cryptonize.it. I also found another listing in the gaming section that seems to say BCH but prices things in BCH + BSV, steamgamekeys.

![image](https://user-images.githubusercontent.com/922233/49732054-e2d6bb80-fcaf-11e8-823d-d16b087baaca.png)

Not sure what is going on there.

**Comment by kenman345** [comment]
Added the BSV tag and using it with Othercrypto tag in the UI. This will mean either or both `bsv` and `othercrypto` tags being set to true will cause the calculations and UI to indicate they accept other crypto. at least this way we can easily reverse it if they come back to BCH

**Comment by kenman345** [comment]
Is this complete? The bot is capable of you opening an issue and commanding the bot to flip BSV and/or BCH. It will add in BSV tag when it’s true.

**Comment by EchterAgo** [comment]
There are still a few I want to monitor, yours.org, cryptonize.it, and CryptoShoppe. CryptoShoppe seems to be back up and is now a Bitcoin SV / Gaming forum that doesn't accept payments, so I'll make a commit to remove it. Cryptonize.it is now under maintenance. Should we just flip yours.org to BSV? Pretty safe to say it will be BSV when Ryan fixes it.
