### ISSUE TITLE
I accept Bitcoin, would like to add to your community.  

### ISSUE THREAD

**Issue by kmajor** [acceptbitcoincash/acceptbitcoincash#146]
I've got 2 sites:
https://sunkratom.com
https://sunkratom.com.tw (Chinese)

Great work keeping the community thriving. 

Viva Crypto...

**Comment by kmajor** [comment]
Looks like you guys are looking for a bit more info as well. 
Sun Kratom is a Taiwan based Kratom vendor. We are an online retail store, the number one Kratom vendor in Taiwan. 

https://facebook.com/sunkratom
https://twitter.com/sunkratom

![sun-kratom-logo-600-web](https://user-images.githubusercontent.com/3528479/30978838-590320ec-a4ae-11e7-9c5e-e9f0689e0717.jpg)

**Comment by rawb0t** [comment]
After chatting with sunkratom on facebook, I've learned they also accept Bitcoin Cash, albeit manually. So whoever adds that make sure to note that as well.
