### ISSUE TITLE
Remove Yours.org and Blockpress.com

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1465]
Neither of them have been functional for a while due to lack of maintenance, with Blockpress even letting its https certificate go invalid. The developers have also went on to work on other projects in bsv.  Please remove them.

**Comment by kenman345** [comment]
Yours is covered in changes for #1457

We are opting for moving sites that are expected to reopen as BSV to supporting BSV but not BCH so as to be more accurate without removing them entirely.

**Comment by EchterAgo** [comment]
Yours.org is currently not functional, but they have not abandoned it, so I think we should wait with removing them. Blockpress does seem abandoned with no indication that it will be working again in the future. How long has it been like that?

**Comment by EchterAgo** [comment]
I got no response from any offical accounts of blockpress or from etherbid, who posted the first announcement and I think started it, so I think we should remove Blockpress. I'll make a pull request for it.
