### ISSUE TITLE
Create a 'bcc only' filtered view to easily see which merchants accept it right now

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#153]
What do we need for this? It should be easy to add a cas class bcc-yes and bcc-no to each row element in the tables and filter from there. 

In Jekyll would we just still use JS and a toggle to change up if bcc-no classed rows are hidden or not? 

where would we put this toggle?

**Comment by kenman345** [comment]
I think @t0p0lin0  and I will be able to tackle this along with other filtering support needed in the site.

**Comment by t0p0lin0** [comment]
Implemented in #205 - Closing this issue.
