### ISSUE TITLE
Crosspost Alfatop.me to Utilities

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1542]
Alfatop.me is currently linked under "Crypto services", considering that it deals exclusively in mobile top ups, it seems appropriate to have it listed under "Utilities" too.

**Comment by EchterAgo** [comment]
Or communications, which one is the better fit?

**Comment by imaginaryusername** [comment]
I'll say both, but if we have to pick one, probably Utilities where there are already phone services (as opposed to SMS).

**Comment by EchterAgo** [comment]
I added it to both.
