### ISSUE TITLE
Add Alfacoins to Payments

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1543]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**Alfacoins**}} to the {{**Payments**}} category. Details follow:

```yml

  name: Alfacoins
  url: https://www.alfacoins.com/
  img: https://www.alfacoins.com/files/a/logo.svg
  twitter: https://twitter.com/ALFAtopme
  bch: yes
  bsv: no
  btc: yes
  othercrypto: yes
  doc: https://www.alfacoins.com/faq

**Comment by EchterAgo** [comment]
I added it already, but it is not on the live site yet. You can see it under https://beta.acceptbitco.in/ . We really need the updated version to be deployed.
