### ISSUE TITLE
Food: Two Restaurants

### ISSUE THREAD

**Issue by maemon** [acceptbitcoincash/acceptbitcoincash#156]
Hey, please add these 2 restaurants in japan which accept BCH to the "Food" category.

Sushi-Bar Numazuko Ginza 1st | https://www.tripadvisor.com/Restaurant_Review-g1066444-d7908006-Reviews-Sushi_Bar_Numazuko_Ginza_1st-Chuo_Tokyo_Tokyo_Prefecture_Kanto.html

Daikanyama O'KOK | https://tabelog.com/en/tokyo/A1303/A130303/13167038/

**Comment by n9jd34x04l151ho4** [comment]
Mostly the site appears to be geared towards accepting payments internationally. The current Food category works for international chains like Starbucks etc. But if there are restaurants in specific cities we might need to separate out the restaurants/cafes into different cities/countries to distinguish them from the international options. Eventually there might be quite a lot of them. So it would be good to pick your current city out of a list and then go there to spend your Bitcoin Cash.

**Comment by t0p0lin0** [comment]
Closing due to complexity of where to add these.
