### ISSUE TITLE
"Add a site or correction" button seems to not work

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1582]
On the lower right we have the "Add a site or correction" button represented by a white plus in a green circle. It is not doing anything when I click it.

![image](https://user-images.githubusercontent.com/922233/56196233-a00f6080-6060-11e9-8c24-7737034df290.png)

**Comment by kenman345** [comment]
the button should be linking to the additions request form if memory serves

**Comment by EchterAgo** [comment]
Yea, it think it should. I also just tested with Edge + Firefox, but those also don't do anything.
