### ISSUE TITLE
How to write to the individual businesses

### ISSUE THREAD

**Issue by Uo124** [acceptbitcoincash/acceptbitcoincash#159]
Maybe creating a discussion place, a discord group, to outline and discuss good writings, and some possible templates. Each template having in consideration the website that would be in focus in the discussion and the needs of each business specifically. 
Then where appropriate, posting the letters on the main accept bitcoin.cash website. Having a place for that. Trying not to spam those costumer supports, so probably setting a count of number of messages needed to be sent?

**Comment by kenman345** [comment]
We have a slack group, we have a contributing guideline here: https://github.com/acceptbitcoincash/acceptbitcoincash/blob/master/CONTRIBUTING.md

Are you saying we should have discussion groups for each individual merchant that we are listing? It would be hard to manage and an endless battle to maintain a focused discussion. I also do not think that enough activity is happening with most merchants that warrant discussion groups like that.

**Comment by kenman345** [comment]
Are you perhaps suggesting something like this: https://vote.bitcoin.com/

**Comment by Uo124** [comment]
Wasn't the goal of this website also to get in contact with merchants, that do not accept yet bitcoin cash?

**Comment by t0p0lin0** [comment]
There are plans to re-work the content from within the Merchants call-to-action button at the bottom of the site, but coming up with good content is the daunting part. We'll get there, but it's certainly an important concern to the project, and making it easy for merchants to discover/accept Bitcoin Cash overall.

**Comment by kenman345** [comment]
not sure whats the status but i'm for closing this or the other ticket around this
