### ISSUE TITLE
Remove "Xpresso" from category "food" and change entry on "Coffeecoin"

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1634]
https://www.xpressoutah.com/ leads to a "website expired" page, probably safe to assume no longer functional. Please remove. 

I also checked the "Coffeecoin" website, it seems like they no longer accept BCH (only BTC/ETH/LTC); furthermore it seems more like a website to sell tokens more than coffee, so a switch to "Crypto services" seem appropriate.

**Comment by EchterAgo** [comment]
We don't directly remove websites that are down, but I put that website on my list of websites to watch. If its still down in a month or so I'll remove it.

I'll remove Coffeecoin then as we don't list coin offerings. They used to sell coffee directly for BCH previously, I ordered from them :\
