### ISSUE TITLE
Requesting to remove switch.at

### ISSUE THREAD

**Issue by simonri** [acceptbitcoincash/acceptbitcoincash#1643]
Requesting to remove **switch.at** from the site because they only accept Core.

**Comment by kenman345** [comment]
we dont remove sites if they only accept BTC. We're not going to stoop to petty tactics to make ourselves look better. We can use this opportunity to try and bring awareness to them about BCH and its advantages to them as a vendor.

**Comment by simonri** [comment]
Sorry wrong from me. They do only accept BTC not BCH. I request to change this in ulilities.yml.

**Comment by kenman345** [comment]
reopened so we can see it if discussion continues here before the PR gets merged

**Comment by EchterAgo** [comment]
Nope, I checked, they accept BCH & BTC using BitPay:

![image](https://user-images.githubusercontent.com/922233/60281287-e0c40980-992e-11e9-952f-0ae74a1fd288.png)

**Comment by EchterAgo** [comment]
@simonri if you have more information, please reopen.

**Comment by georgengelmann** [comment]
That's strange. I asked them via e-mail.

"Leider ist eine Bezahlung per BitCoin Cash nicht möglich." (Unfortunately Bitcoin Cash payment is not possible) - switch.at via e-mail

Maybe they don't even know about it? (BitPay allowing BCH payments)

**Comment by EchterAgo** [comment]
Yea, they probably don't know about it.
