### ISSUE TITLE
Requesting to remove http://maxkite.wixsite.com/vvedene

### ISSUE THREAD

**Issue by simonri** [acceptbitcoincash/acceptbitcoincash#1645]
Requesting to remove **http://maxkite.wixsite.com/vvedene** in `accomodation.yml` from the list. Multiple website scanners detect it as scam or phishing.

https://www.mywot.com/scorecard/maxkite.wixsite.com
https://i.imgur.com/63rgEAn.png

**Comment by EchterAgo** [comment]
Please add a commit to remove it in PR #1642
