### ISSUE TITLE
Health: Imeddo Inc

### ISSUE THREAD

**Issue by Healthwarrior1** [acceptbitcoincash/acceptbitcoincash#166]
Hi, 

I would like to add my company IMEDDO INC www.imeddo.com to the list of companies that accept Bitcoin Cash.  We sell Health Supplements and would like to add it to the HEALTH category as well as the FOOD category of businesses as Health supplements are legally "Food".  Please assist.  

Thankyou, 

Dr. Ben

**Comment by kenman345** [comment]
We only list the same company if its separate services that warrant multiple listings. I think your site belongs in the Health section though, We would be happy to list you there if that was okay.

**Comment by Healthwarrior1** [comment]
That would be great! Let me know if you need anything very excited!


On Mon, October 9, 2017 12:27 pm, Ken Salomon wrote:
> We only list the same company if its separate services that warrant
> multiple listings. I think your site belongs in the Health section
> though, We would be happy to list you there if that was okay.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/acceptbitcoincash/acceptbitcoincash/issues/166#issuecom
> ment-335247248


Dr. A. Ben Goins MS DSM
President
iMedDo Inc NeuSilver(tm)
www.iMedDo.com
(832) 919-NEUS [6387]
9191 NE 41st CT
Anthony, FL 32617

**Comment by kenman345** [comment]
do you have a square logo?

**Comment by Healthwarrior1** [comment]
Yes,

Let me know if either of these will work or if you need a certain image
size or type and I"ll try to make one.   Attached is my official logo
(imeddo.jpg) which is kinda more rectangular than square but might work, 
Also is the image of the NeuMandala artwork which is a definitely a square
image and can be used to represent my company as a stand in logo if a
square image is needed (neumandalla_top.jpg) and also I included a picture
of my products (I have 3 each has its own logo NeuSilver, NeuIodine,
NeuGold) in case you need that.  Let me know if you need anything very
excited to be listed on your site.




On Mon, October 9, 2017 2:19 pm, Ken Salomon wrote:
> do you have a square logo?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/acceptbitcoincash/acceptbitcoincash/issues/166#issuecom
> ment-335274336


Dr. A. Ben Goins MS DSM
President
iMedDo Inc NeuSilver(tm)
www.iMedDo.com
(832) 919-NEUS [6387]
9191 NE 41st CT
Anthony, FL 32617

**Comment by kenman345** [comment]
I do not see either of those, do you have urls you can provide that link me to those images?

**Comment by rawb0t** [comment]
Looking through your checkout process, I don't see a way to pay with Bitcoin Cash. Can you please double check?

**Comment by Healthwarrior1** [comment]
Hi Rob,

Yes you can pay with bitcoin cash.  It's not in the checkout process,
instead on the main page (imeddo.com) under "NEW! Crypto Payments Accepted
including Bitcoin Cash" it says underneath to the right of the castle
picture:

"Bitcoin Cash (BCH) use crypto-address 18XstiSVL1kvi5i5rBFx88ybDHh31AyL7L
for payment, and also email us with your shipping address."

For someone to order and pay with bitcoin cash they would need to email me
their shipping address and confirm their order and then send payment of
~0.5 BCH(BCC) [~150 USD value] assuming they want the 3-pack Ultimate
Detox System 6 month supply (NeuSilver, NeuIodine & NeuGold to that crypto
address.

Let me know if you have any questions, or think I should change or clarify
anything on my website to better support it.


Thankyou,

Dr. Ben




On Fri, October 20, 2017 12:18 pm, Rob Danielson wrote:
> Looking through your checkout process, I don't see a way to pay with
> Bitcoin Cash. Can you please double check?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/acceptbitcoincash/acceptbitcoincash/issues/166#issuecom
> ment-338284533


Dr. A. Ben Goins MS DSM
President
iMedDo Inc NeuSilver(tm)
www.iMedDo.com
(832) 919-NEUS [6387]
9191 NE 41st CT
Anthony, FL 32617

**Comment by Healthwarrior1** [comment]
Hi Rob,

I figured out the problem and fixed it.  Now you can also check out using
Bitcoin Cash using the Coinpayments.net checkout button.

Before they didn't support Bitcoin Cash, so to accept it people had to
send it directly to my Bitcoin cash address, but now is easier as they can
use the Coinpayments.net checkout feature.

Let me know if you have any further questions.

Thankyou,

Dr. Ben




On Fri, October 20, 2017 12:18 pm, Rob Danielson wrote:
> Looking through your checkout process, I don't see a way to pay with
> Bitcoin Cash. Can you please double check?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/acceptbitcoincash/acceptbitcoincash/issues/166#issuecom
> ment-338284533


Dr. A. Ben Goins MS DSM
President
iMedDo Inc NeuSilver(tm)
www.iMedDo.com
(832) 919-NEUS [6387]
9191 NE 41st CT
Anthony, FL 32617

**Comment by Healthwarrior1** [comment]
Fixed it.

On Fri, October 20, 2017 12:18 pm, Rob Danielson wrote:
> Looking through your checkout process, I don't see a way to pay with
> Bitcoin Cash. Can you please double check?
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/acceptbitcoincash/acceptbitcoincash/issues/166#issuecom
> ment-338284533


Dr. A. Ben Goins MS DSM
President
iMedDo Inc NeuSilver(tm)
www.iMedDo.com
(832) 919-NEUS [6387]
9191 NE 41st CT
Anthony, FL 32617
