### ISSUE TITLE
Add 'Uploaded.net' to the 'Cloud Computing' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#1662]
Requesting to add 'Uploaded.net' to the 'Cloud Computing' category. 

Details follow: 
```yml 
- name: Uploaded.net
  url: https://uploaded.net/
  img: Uploadednet.png
  bch: true
  btc: true
  othercrypto: false
  twitter: ul_to
```

Resources for adding this merchant:
Logo Provided:
![ProvidedLogoURL](https://pbs.twimg.com/profile_images/3750163830/d616af3488431ff6362d2d6296d5b1b7_bigger.png)
Twitter Profile Image (48x48):
![TwitterProfileImageURL](https://pbs.twimg.com/profile_images/3750163830/d616af3488431ff6362d2d6296d5b1b7_normal.png)
[Link to Uploaded.net](https://uploaded.net/)
Check their Twitter Page: [twitter.com/ul_to](https://twitter.com/ul_to)
Maybe you might want to check their [Alexa Rank](https://www.alexa.com/siteinfo/uploaded.net/)
Maybe you might want to check [Scam Adviser](https://www.scamadviser.com/check-website/uploaded.net/)
Maybe you might want to check [Trust Pilot](https://www.trustpilot.com/review/uploaded.net/)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

**Comment by EchterAgo** [comment]
They do not accept crypto.
