### ISSUE TITLE
Remove 'easy.gr' from 'Hosting/VPS'

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1701]
These guys seem quite hostile to customers who were seeking privacy, and have some questionably customer-support policies in following up.
https://twitter.com/im_uname/status/1183273532429496320
https://twitter.com/im_uname/status/1183456674759098368

**Comment by kenman345** [comment]
I created a warning for the listing to inform people. We do not remove sites due to politics unless they are not actually providing the advertised service they are listed for.

Since they are still a hosting provider, they stay. But your concerns are handled for those that might benefit from it
