### ISSUE TITLE
Switch "Purism" in "Retail" from not accepting to accepting Bitcoin Cash

### ISSUE THREAD

**Issue by imaginaryusername** [acceptbitcoincash/acceptbitcoincash#1710]
Documentation: https://puri.sm/faq/, scroll down to "What payments do you accept?"

**Comment by imaginaryusername** [comment]
I see, might have been mistaken then =\

**Comment by EchterAgo** [comment]
When GloBee stopped accepting BCH I checked Puri.sm and BCH was listed but "not available".
