### ISSUE TITLE
Retail: FudMart NG

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#173]
URL: https://fudmartng.com/
Source: https://fudmartng.com/wp-content/uploads/2017/10/IMG-20171006-WA0000d.jpg
Facebook: https://www.facebook.com/fudmartng/
Twitter: https://twitter.com/fudmartng

**Comment by kenman345** [comment]
Note:

btc: Yes
bcc: Yes
othercrypto: Yes
