### ISSUE TITLE
Discussion: use imgbot on github?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#178]
https://github.com/apps/imgbot

it will make PRs like this: https://github.com/2factorauth/twofactorauth/pull/2802

@zquestz @t0p0lin0  thoughts?

**Comment by rawb0t** [comment]
need? no. do it anyway? yes. @t0p0lin0 ?

**Comment by t0p0lin0** [comment]
That's pretty cool, and provided it's unobtrusive, then I would be fine with integrating it.

**Comment by rawb0t** [comment]
Seems pretty unobtrusive. Looks like it just submits PRs. Plug it up!

**Comment by t0p0lin0** [comment]
Alright, it's been added. Let's see how she goes.
