### ISSUE TITLE
https://www.piixpay.com/web/

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#184]
Not sure what they do but they support BCC now.

**Comment by m4ktub** [comment]
They are a gateway between Bitcoin Cash and bank transfers. You pay them Bitcoin Cash, they wire the money using SEPA. They are in the "Payments" category, I believe.

**Comment by kenman345** [comment]
Sounds like Living room of satoshi, so I think its going to fall into the Crypto-services section.
