### ISSUE TITLE
CryptoGraffiti.info now accepts Bitcoin Cash exclusively

### ISSUE THREAD

**Issue by 1Hyena** [acceptbitcoincash/acceptbitcoincash#187]
announcement: https://redd.it/76lv0b
link: http://cryptograffiti.info

**Comment by t0p0lin0** [comment]
Very cool site/service. We'll get this added, but can you recommend a category @1Hyena ? I might suggest one of the following:

- Communication
- Crypto Services
- Social
- Other (as a fallback)

Let us know of any preference of yours, if you've got one. Thanks for contributing this!

**Comment by 1Hyena** [comment]
@t0p0lin0 
crypto services would probably suit the best
although people have also called it a specialized block explorer

**Comment by t0p0lin0** [comment]
_Crypto Services_ it is then. I can see how it might be called a "specialized block explorer", but even in that case, we list block explorers under Crypto Services, so looks like we've got our answer.
