### ISSUE TITLE
Change name of our primary branch?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#1878]
So I might have been living under a rock and not understanding why but I have noticed a trend to rename or move away from the use of "master" as a branch name. It was only today I realized this was in an effort to remove unconscious bias and normalizing the use of the terms master/slave in everyday life. 

My personal feelings are that since we always strive to be inclusive and sensitive to others beliefs, that this may be something worth proceeding with.

I wanted to pose the question to everyone. Should we be following the footsteps of others and eliminating the use of a master branch and instead give it a more apt name.

I am not very experienced renaming a head branch, so maybe someone can chime in with steps we would need to take to accomplish this task if we decide to proceed. At the top of my head, I know the following would need to be done after/during a name change:
- Revise Travis-CI builds through Travis website to change over branch name and scheduling.
- Revise name of merging branch and branching branch names in ABCBot to the name of our new primary branch.

I also think before we can rename we might need to clean out pull requests, but again, not sure how everything works if we just rename the branch.

**Comment by hegjon** [comment]
> So I might have been living under a rock and not understanding why but I have noticed a trend to rename or move away from the use of "master" as a branch name. It was only today I realized this was in an effort to remove unconscious bias and normalizing the use of the terms master/slave in everyday life.

I have never thought about it or heard about this thinking before.

> My personal feelings are that since we always strive to be inclusive and sensitive to others beliefs, that this may be something worth proceeding with.

Can you explain why calling it the default branch master is bad? And who would not feel included?

**Comment by kenman345** [comment]
I'll just post this article [here](https://www.bbc.com/news/technology-53050955). I am not the best at explaining everything but for the most part its to eliminate the usage of phrasing that may otherwise be used in a racially charged way.

**Comment by zquestz** [comment]
Feel free to change it, but honestly I think the arguments for moving away from a `master` branch are nuts. I do agree that `master/slave` terminology for databases is not great, but for git, the master branch is merely the main branch and doesn't have a negative connotation. My 2 cents.

**Comment by kenman345** [comment]
Thank you for chiming in.

I’ve looked over the work needed and don’t think it’s worth the effort in
the short term unless demand is there. I just wanted to make sure we had a
discussion about it and allow anyone that might find issue the chance to
respond. In that faith, I shall leave this open until this reaches 1 week
old and then close it. If anyone has any issues with us keeping the master
branch as is, please use this time to express your concerns/views.

Hope everyone is staying safe!
