### ISSUE TITLE
https://pool.btc.com support bitcoin cash mining

### ISSUE THREAD

**Issue by btccomgogo** [acceptbitcoincash/acceptbitcoincash#188]
announcement: https://btcapp.api.btc.com/v1/h/news/4903?v=2
link: https://pool.btc.com

**Comment by kenman345** [comment]
Very interesting. I will discuss with the others about where this should go. I have always said that we might need a pool/mining section but if we do not decide to add this to a new section like that, I believe it would go to the crypto-services section. Thank you for bringing this to our attention
