### ISSUE TITLE
sections with no sites

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#192]
![2017-10-20 13_23_21-_includes_desktop-table html_ working tree - tortoisegitmerge](https://user-images.githubusercontent.com/10980567/31833957-42d885a8-b59a-11e7-8434-f6240465f380.png)

Test and confirm this is a solution.

**Comment by t0p0lin0** [comment]
Resolved in 36541a6926a684c57c544d49d67b3404900ea417
