### ISSUE TITLE
Security/VPN https://crypticvpn.com/ accepts Bitcoin Cash

### ISSUE THREAD

**Issue by coinstash** [acceptbitcoincash/acceptbitcoincash#199]
https://www.reddit.com/r/btc/comments/77p6dw/crypticvpn_accepts_bitcoin_cash/

**Comment by rawb0t** [comment]
https://github.com/acceptbitcoincash/acceptbitcoincash/commit/854e287afd06fc0022830714b7d232e6a1cb28f9

**Comment by coinstash** [comment]
Oops, missed that. Thanks.
