### ISSUE TITLE
Fix row highlight color for BTC supported, but not BCC 

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#20]
As it stands now, the site will colour the row of a merchant _green_ if BTC is supported, but BCC is not. Since this is all about Bitcoin Cash, the row color should be _red_ in any case that BCC is **NOT** (fully) supported.

**Comment by kenman345** [comment]
I only see it coloring the cell green around the bitcoin logo.

**Comment by t0p0lin0** [comment]
Perfect, that's what I want @kenman345 -- Basically, the name should be on a green background *only* if Bitcoin Cash is supported.
