### ISSUE TITLE
"10 Reasons Your Business Should Accept Bitcoin Cash"

### ISSUE THREAD

**Issue by memalley** [acceptbitcoincash/acceptbitcoincash#208]
To be included in the "Merchants" CTA modal.

**Comment by t0p0lin0** [comment]
Great idea to help improve the content with regards to educating merchants to the benefits of accepting Bitcoin Cash!

**Comment by kenman345** [comment]
Maybe we should log this in our project tasks and close out the ticket. This feature would need to be grouped with other proposed changes to add more pages to the site anyways.

**Comment by kenman345** [comment]
Shall we close this?
