### ISSUE TITLE
Scam? Internoc24 might be a scam service

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#210]
Based on information here: https://www.reddit.com/r/btc/comments/78ik63/beware_internoc24_hosting_scam_accepts_bitcoin/

**Comment by kenman345** [comment]
We should evaluate the story and remove them if this is true. Currently at work but will take a look tonight. Lets get this done before our next deploy.

Would appreciate the help @rawb0t @zquestz @t0p0lin0

**Comment by rawb0t** [comment]
They delivered the service, and that becomes a liability issue anyway. caveat emptor.
