### ISSUE TITLE
Use sections.yml to implement script exceptions

### ISSUE THREAD

**Issue by jrkong** [acceptbitcoincash/acceptbitcoincash#254]
#168 while the suggestion @kenman345  is great and it should be how exceptions are implemented in the future the scripts works for now and we need this PR so #241 has the proper numbers.

This issue is here so it will be fixed in the future.

**Comment by t0p0lin0** [comment]
@jrkong - Can you update on status/whether or not this is still necessary? I am a bit lost in tracing it back, but I do know that we have the supported count working via `bchAccepted.py`. No rush on your response, but thanks in advance.

**Comment by jrkong** [comment]
Just finished my last exam today so I'll be more active starting tomorrow. This issue shouldn't be a problem anymore because we removed the contents in financial.yml. When this issue was made financial.yml was populated with sites that weren't being used by the site which messed up the count. Now that that's gone, as far as bchAccepted.py is concerned, the count should be accurate. 

imgDebugger.py will still benefit from this for sure because it thinks sections.yml is a legitimate section so it creates a Sections directory under the img folder but other than that I can't think of any immediate effects fixing this issue will cause. 

That said, this might be a good long-term goal just to make some of the scripts more robust and expandable in the future.

**Comment by t0p0lin0** [comment]
Nice. Thanks for the quick reply. I'll close this issue then, and please open another if/when you start to re-evaluate any work needed on the `scripts/` - Cheers!
