### ISSUE TITLE
Hide categories without any BCH sites when BCH filter is active

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#259]
Do a count on items with `bch: yes` and if none, apply a class to the relevant elements to extend the BCH filtering function.

**Comment by zquestz** [comment]
I can't wait till this is implemented! Also you might want to default the site to BCH only. Then it will be a lot more focused on companies that already support it. Then they can toggle it off if they want to send tweets/messages to companies that don't support it yet.
