### ISSUE TITLE
KaMoney Brasil is now accepting #BitcoinCash

### ISSUE THREAD

**Issue by VitorAugusto** [acceptbitcoincash/acceptbitcoincash#275]
Requesting to add KaMoney Brasil to the Crypto Services and Payments category,

- name: KaMoney Brasil
  url: https://www.kamoney.com.br/
  twitter: kamoneybrasil
  facebook: kamoneybrasil
  img: https://pbs.twimg.com/profile_images/878815743932080128/bO8IolFQ_400x400.jpg
  bcc: yes
  btc: yes
  othercrypto: yes
  doc: https://twitter.com/kamoneybrasil/status/930527194803302400

```

Add more information here if necessary

**Comment by VitorAugusto** [comment]
Add to Crypto Services and Payments category,

**Comment by t0p0lin0** [comment]
Thanks for this addition! However, we currently have a policy of adding a site to _only one_ category. Which would you prefer in this case? I would suggest Crypto Services, as I believe this is a service similar to Living Room of Satoshi (pay traditional bills with crypto). Thanks again!

**Comment by VitorAugusto** [comment]
Crypto Services only , yes !! , as the service is similar to the Living Room of Satoshi.

**Comment by t0p0lin0** [comment]
Wonderful. Thanks for confirming so quickly. We'll be sure to merge this change in soon. Cheers!
