### ISSUE TITLE
Duplicate name with different URL

### ISSUE THREAD

**Issue by aciidic** [acceptbitcoincash/acceptbitcoincash#297]
Under VPS/Hosting section;

CloudAtCost is listed twice - assuming this is a mistake?
Once with url http://cloudatcost.com/
and URL https://cloud9hosting.com/

**Comment by t0p0lin0** [comment]
Thank you for catching this mistake and taking the time to submit an issue. It is fixed in #305 and will be applied to the live site shortly. Cheers.
