### ISSUE TITLE
My suggestion: include Porn's sites category

### ISSUE THREAD

**Issue by xskl0** [acceptbitcoincash/acceptbitcoincash#353]
Hi!

I think https://acceptbitcoin.cash/ should have a section of porn sites like Chaturbate, that kind of sites use money to sell tokens/ premiums and theirs users don't like to have that transaction linked with banks. Now that they can't use bitcoin anymore maybe they can become BCH pioneers.

Example:
Chaturbate (category: porn industry)

- name: Chaturbate
  url: www.chaturbate.com
  twitter: chaturbate
  facebook: ???
  img: https://ssl-ccstatic.highwebmedia.com/images/logo_xmas.svg
  bch: NO
  btc: YES
  othercrypto: NO
  doc:

Bitcoin announcement: https://blog.chaturbate.com/news-and-announcements/purchase-tokens-with-bitcoin/

Bitcointalk.org- "Getting porn sites to accept bitcoin": https://bitcointalk.org/index.php?topic=22946.0
```

Best Regards,
-xskl0

**Comment by t0p0lin0** [comment]
Thanks for your submission. While we haven't quite made the decision to display adult material on the live site just yet, we are actively collecting [merchants within the `xxx.yml` file](https://github.com/acceptbitcoincash/acceptbitcoincash/blob/master/_data/xxx.yml) to be used at a later date, possibly on a separate "Adult" page preceded by a warning.
