### ISSUE TITLE
Implement CSV for listings instead of YAML

### ISSUE THREAD

**Issue by olafghanizadeh** [acceptbitcoincash/acceptbitcoincash#364]
Hey guys!

I was looking at this repo and I thought it might be a good idea to implement CSV instead of YAML to create the database of merchants. With a CSV file you could for instance host it on Google Sheets or Airtable and allow people to contribute and add their business instead of having to do it through Github.

Check the Jekyll data files spec:
https://jekyllrb.com/docs/datafiles/

**Comment by t0p0lin0** [comment]
Great idea, thanks, however I don't quite think we're ready to refactor how the site _currently_ works. We are a small team doing this on spare time, which seems to be limited for most of us. We are happy to analyze/discuss any pull requests though!

**Comment by kenman345** [comment]
This is possible, but I am closing this issue for the time being. I do not think the advantages gained will be worthwhile with the level of effort that it takes and the potential trolling such a wide open form could cause. But we are implementing some changes to requesting sites be added that will streamline the process for users and the maintainers.
