### ISSUE TITLE
Add a Non-profit or Charity category

### ISSUE THREAD

**Issue by t0p0lin0** [acceptbitcoincash/acceptbitcoincash#376]
Would be used to compile a list of non-profit/charity organizations that accept Bitcoin Cash for donations.

**Comment by kenman345** [comment]
I'm thinking a /donate page with non-profits/chairties. Pretty much anything you arent buying or paying for a service but able to use BCH.

Lets add the Bitcoin Cash fund in there too. Move Frostwire off to that. I think Wikileaks accepts it in the store, but also as a donation. Does Red Cross? 

I feel like I'm missing one or two that we have run into in the past.

**Comment by phillipsjk** [comment]
https://archive.org/donate/bitcoin.php

https://www.pathwaystoeducation.ca/donate-bitcoin-cash

Probably still missing some ;)

**Comment by t0p0lin0** [comment]
Bitcoin Cash (BCH) Lists of Charities:

- Run 2 Rescue - http://run2rescue.com/bitcoin.php
- Internet Archive - https://archive.org/donate/bitcoin.php
- Maps - http://www.maps.org/donate-redirect/cryptocurrency
- Deep Center - http://www.deepkids.com/give
- Gyanada Foundation - https://twitter.com/Gyanada_Fdn (not listed on their website, just bch addr in Twitter profile)

Bitcoin (BTC) Lists of Charities:

- http://bitcoinforcharity.com/bitcoin-charity-list

**Comment by ftrader** [comment]
Fareshare : http://fareshare.net.au 

https://twitter.com/FareShare1/status/949041934453981185

**Comment by joshmcintyre** [comment]
Someone was asking about this on Reddit today. I'll have some time this weekend so I can get to work on adding this.

**Comment by kenman345** [comment]
It appears Tutanota is a non-profit

**Comment by kenman345** [comment]
erowid.... https://www.reddit.com/r/btc/comments/830svj/erowid_accepts_bitcoin_cash_the_pineapple_fund_is/
