### ISSUE TITLE
Consider using square/green logo for better visibility

### ISSUE THREAD

**Issue by nshopik** [acceptbitcoincash/acceptbitcoincash#403]
Current rectangular logo is have visibility problem when scaled down to favicon. Also same orange color still could create confusion even for advanced users. As different coloring help quickly grasp for what you are looking even via peripheral vision

https://github.com/wilsonwastaken/BCH-design provide with good design assets for BCH brand

**Comment by t0p0lin0** [comment]
We're certainly considering it, and I personally really like the logo you linked to. Will keep this issue active, and in the near future, I'm sure the team will come to a conclusion.

Thanks for the suggestion and linking to that repo full of high quality assets.

**Comment by kenman345** [comment]
@t0p0lin0  can we close this? Its this something we're doing or have done?

**Comment by kenman345** [comment]
would like to close this. I think we'e okay with round logos for now.

**Comment by kenman345** [comment]
can always re-open but for nothing to happen on this issue, it might as well be closed
