### ISSUE TITLE
Splitting up Cryptocurrencies category

### ISSUE THREAD

**Issue by deadr0ck** [acceptbitcoincash/acceptbitcoincash#47]
As I'm about to add another 45 entries to the 'cryptocurrencies' section, its getting pretty busy. I'd like to propose splitting it up into these:

- Exchanges
- Wallets
- Crypto Services (ie. payment processors, mixers, etc)

We could optionally prefix both Exchanges & Wallets with "Crypto" too if anyone doesn't think they are self-explanatory.

Please let me know what you think

**Comment by kenman345** [comment]
I am okay with it. I dont think wallet needs it but maybe exchanges would benefit from the Crypto prefix.

**Comment by t0p0lin0** [comment]
I'm absolutely OK with this. Great idea. Also agree that it should be:

- Crypto Exchanges
- Crypto Services
- Wallets

I think Wallets makes sense to anyone using BTC/BCC, unless they would somehow think of leather wallets before a crypto wallet :thinking:
