### ISSUE TITLE
Update 'Bitcoin Games' listing in Gambling category

### ISSUE THREAD

**Issue by davidshares** [acceptbitcoincash/acceptbitcoincash#484]
https://www.reddit.com/r/btc/comments/7mnlvm/bitcoincoms_cash_games_have_arrived/

Bitcoin.com now fully supports BCH so the listing needs to remove the status flag so it shows up in gambling section properly.

**Comment by kenman345** [comment]
Bitcoin.com is already listed.

**Comment by davidshares** [comment]
@kenman345 It's listed under Mining (pool) and Wallets (wallet), it's separated.

**Comment by kenman345** [comment]
https://acceptbitcoin.cash/#gambling

Listed as Bitcoin Games. But your request is valid since it apparently now supports BCH and is not just working to implement it. I am reopening this issue and renaming the task

**Comment by davidshares** [comment]
@kenman345 great thanks. Strange thing is I searched a couple times for 'bitcoin.com' and only the two I mentioned above showed. Thanks for reopening!

**Comment by kenman345** [comment]
This is live on the site now
