### ISSUE TITLE
Shall we at least update this url to be HTTPS?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#491]
https://github.com/acceptbitcoincash/acceptbitcoincash/blob/cabdbd567f96b5f7f647bab7b6c0630ec92a3f8b/_config.yml#L8

**Comment by kenman345** [comment]
@joshmcintyre  so originally we used the main URL but Twitter blocked tweets that had that url in it so we changed it to useBitcoin.cash for the tweets. I am merely proposing we make it https in one of our next PRs.

**Comment by joshmcintyre** [comment]
Yes please. HTTPS everywhere possible!
