### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by hegjon** [acceptbitcoincash/acceptbitcoincash#538]
I was searching for `openbazaar`, but I got no hits because it is added as `Open Bazaar`.

It would be nice if the search ignores whitespace.

**Comment by kenman345** [comment]
@t0p0lin0  this is your field on the search stuff. Would love to know more myself about it so I can help tweak it in the future

**Comment by t0p0lin0** [comment]
Right now the site uses [Jets.js - Native CSS search engine](https://jets.js.org/), and it doesn't look like it's possible after testing with the demo elements on that page.

**Comment by t0p0lin0** [comment]
Closing to keep things clean, but this can be resubmitted in the future if necessary.
