### ISSUE TITLE
The Swedish Twitter template translation is wrong

### ISSUE THREAD

**Issue by hegjon** [acceptbitcoincash/acceptbitcoincash#543]
From the twitter feed:
> Xskl0 ⚡BCH PLS⚡ @xskl9
> 
> Säkerhet är viktigt, @Inleed. Vänligen lägg till two factor authentication på er hemsida. http://usebitcoin.cash

The translation is something along this: Security is important, Please add two factors authentication to your homepage.

**Comment by kenman345** [comment]
yea we forked off them and never hit that......ooops. Care to fix please and thank you?

@t0p0lin0  are we actually using those yet? I feel like we should be for at least the tweets if not alt text for everything we can

**Comment by hegjon** [comment]
I am not able to write Swedish, but I can use Google Translate and see if the translation seems correct.

**Comment by t0p0lin0** [comment]
@kenman345 - Apparently we are using them. Take a look at **Inleed** (_Hosting_) and note `lang: sv`. Thanks for catching this in the first place and opening an issue @hegjon.
