### ISSUE TITLE
Open Conversation: Alternative purchasing option prompt

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#577]
I am thinking that while the site is helpful, we have seen a lot of questions in r/btc about "Where can I get a gift card for Amazon.co.uk with BCH?" and "How can I use BCH with XXXX"

I am not sure the level of effort, but I am proposing the idea of an "alt options" tag. This would essentially be a yes/no flag and the effective change is an additional note on the page to say 

> While this merchant does not accept BCH directly, the cryptoservices section has options for merchants you can buy gift cards/credit to this merchant.

Or something like that.

Thoughts? @t0p0lin0  @joshmcintyre @hegjon ?

**Comment by hegjon** [comment]
Maybe use the same column as Bitcoin Cash, but change the background to yellow? and replace the Bitcoin Cash image with a gift card?

**Comment by kenman345** [comment]
If we're focused on getting merchants to accept BCH and on growing user adoption of BCH, we need to give them as many options as possible to use BCH. I think we need to get some feedback from the team and figure out how to proceed. We could move out the BTC column, or potentially just add a card icon next to the listing just like a warning would be. 

For sites that also accept BCH and are supported by eGifter and others, we could move to indicate you can use it directly and indirectly.

**Comment by kenman345** [comment]
I am thinking also we could figure out the UI change but try to keep things less cluttered by implementing a modal for the gift card options, allowing us to show all the gift card providers that aare providing gift cards to a particular site

**Comment by kenman345** [comment]
I would like to revisit this. Please weigh in if you got opinions everyone!
