### ISSUE TITLE
Update bitpay as already supporting BCH

### ISSUE THREAD

**Issue by cashaddressio** [acceptbitcoincash/acceptbitcoincash#624]

**Comment by kenman345** [comment]
Its already that way. We just forgot to remove the status tag so its all weird. Will be fixed in next deploy.

**Comment by hegjon** [comment]
Do we have a way to identify all the merchants on the list that use BitPay? Would it make sense to include an option meta-field that identifies a payment processor?

**Comment by kenman345** [comment]
I had proposed that back when we knew Bitpay would do something like this
months ago. It’s a bit late now is all. It’s already the time we care about
that info
