### ISSUE TITLE
Follow-Up to #607

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#625]
from #607 
Please note that I made this list: [semantics options.txt](https://github.com/acceptbitcoincash/acceptbitcoincash/files/1794921/semantics.options.txt)

In case we decide to change the icon for services....but also, heres the image of what it looks like now: ![screenshot](https://i.imgur.com/WJppYtT.png)

Do we wish to change the icon? I was thinking maybe "fax" or we see whats needed to get semantics 2.3 going properly on our repository and use "handshake"

**Comment by t0p0lin0** [comment]
I think 'fax' is a good one to go with for now. Switching to Semantic UI 2.3 is quick and easy, but again, breaks the section icons that are already there. I didn't have too much time to look at it after that quick attempt, but I will try to see what's going on in more detail if possible.
