### ISSUE TITLE
Vultr now accepts Bitcoin Cash

### ISSUE THREAD

**Issue by ftrader** [acceptbitcoincash/acceptbitcoincash#630]
Vultr is already listed, but currently only for BTC.
As they use Bitpay, their support of Bitcoin Cash has now been confirmed by someone:

https://www.reddit.com/r/btc/comments/834qdf/you_can_now_pay_vultr_bills_with_bch/

**Comment by kenman345** [comment]
shall be in the deploy after we merge in the changed listing. Thanks!
