### ISSUE TITLE
Site improvement suggestion: Geographic ordering of merchants

### ISSUE THREAD

**Issue by conaman551** [acceptbitcoincash/acceptbitcoincash#652]
A visitor to the site needs to be able to search by the location of the merchants, especially as the list grows very large, searching only by category is far too tedious (the are literally millions of shops globally).  coinmap.org is a good example of a user friendly interface, if I want to find any shops accepting bitcoin in a city or country, it works really well, i simply look at a map. It doesn't need to be map style it could just be: find all BCH accepting merchants within X kilometres of X town/city. If I were a coder id go right ahead and contribute the code alas i'm not. Keep up the great work!

**Comment by kenman345** [comment]
Relates to #396 so we will discuss there.
