### ISSUE TITLE
Split out content from 'default.html' into smaller partials

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#759]
@t0p0lin0 I know you refactored some stuff but does the front-matter variables need to be defined on each header of the three main pages when they probably can be in the default.html frontmatter? Not sure if thats how it works but figured we can quickly double check so things like the hashtags and stuff dont ever get out of sync.

**Comment by t0p0lin0** [comment]
This was the one shortcoming that I didn't have time to address, having duplicated header content across those 3 files. Feel free to play around with it and see, but rather than break anything, I decided to avoid making any big changes there.

**Comment by kenman345** [comment]
I will play. I believe we would have to move the global things to the config yml

**Comment by kenman345** [comment]
somewhat doing this in #761
