### ISSUE TITLE
cryptohabit website is down 

### ISSUE THREAD

**Issue by hegjon** [acceptbitcoincash/acceptbitcoincash#790]
The front page of https://cryptohabit.com/ says:

> This Website is Undergoing Maintenance.
> admin@cryptohabit.com

Check again later and see if it is back

**Comment by joshmcintyre** [comment]
CryptoHabit has been down forever...my first PR with AB.C was actually to remove that link.

The owner of this site (@theantnest) reported a while back that it was down/hacked. I don't know if he is still planning to bring it up or not, but it has been months since it's been operable.
