### ISSUE TITLE
Go through and add listings

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#819]
Found https://twitter.com/spendabit

and they seemed to have tweeted out about merchants and some of them do accept BCH. I have made addition requests for a few of them but we have plenty more we can add from those tweets alone.

Hopefully we can get through most of them or they are already listed but this could be a huge resource to filling out the site more.

**Comment by kenman345** [comment]
- [ ] [USBKill.com](https://usbkill.com/) [Twitter](https://twitter.com/USBKill) uses Bitpay and so BTC and BCH support.

**Comment by EchterAgo** [comment]
Lush has been added. I put ACE Hackware on my list of sites to check after 30th of April, when CB discontinues the merchant tools

**Comment by kenman345** [comment]
@EchterAgo Wanna check up on Adamant Barbell and then we can close this?

**Comment by EchterAgo** [comment]
They only accept BTC

**Comment by kenman345** [comment]
Opened up #1036 to handle this. Will close this issue now
