### ISSUE TITLE
https://cryptartica.com/

### ISSUE THREAD

**Issue by coinstash** [acceptbitcoincash/acceptbitcoincash#92]
Needs to be listed.

**Comment by deadr0ck** [comment]
Thanks @coinstash - would you know if they have a square logo we can use? I can use the horizontal one on their site otherwise, it just won't look great at 32x32.

**Comment by kenman345** [comment]
What section shall we add them to? I can add it to my PR if we get a response soon

**Comment by kenman345** [comment]
Fixed in PR #123

**Comment by coinstash** [comment]
Thanks. Sorry I didn't log in for a few days. Too fast for me.
