### ISSUE TITLE
How are we validating that merchants are actually accepting Bitcoin Cash?

### ISSUE THREAD

**Issue by n9jd34x04l151ho4** [acceptbitcoincash/acceptbitcoincash#955]
I registered for Ultraseedbox and attempted to pay with Bitcoin Cash there. They have two options:

Bitcoin Payments (BTC)
Bitcoin & Altcoin via Coingate

So while Coingate accept Bitcoin Cash and other altcoins, this particular merchant does not have that configured properly so you can only pay with BTC. You can't actually change from BTC to some other coin:

![screenshot from 2018-05-13 20-25-17](https://user-images.githubusercontent.com/31981309/39972746-cbeea0e6-56eb-11e8-8d8d-07df4519cd41.png)

I contacted their customer support about it and got back:

![screenshot from 2018-05-13 20-18-12](https://user-images.githubusercontent.com/31981309/39972707-3ea2bfec-56eb-11e8-838f-5fa6eacb4f7d.png)

So for now it appears we should change this part in the Hosting/VPS section:

    - name: Ultraseedbox
      url: https://www.ultraseedbox.com/
      twitter: ultraseedbox
      facebook: ultrasbox
      img: ultraseedbox.png
      bch: yes
      btc: yes
      othercrypto: yes
      doc: https://kb.ultraseedbox.com/display/DOC/Payments

to:

    - name: Ultraseedbox
      url: https://www.ultraseedbox.com/
      twitter: ultraseedbox
      facebook: ultrasbox
      img: ultraseedbox.png
      bch: no
      btc: yes
      othercrypto: no
      doc: https://kb.ultraseedbox.com/display/DOC/Payments

But it brings up a bigger question about how we are validating that the merchants really are supporting BCH? We almost need to create a dummy account and try paying, or at least getting to a screen where you can pay via QR code or whatever to validate them.

**Comment by EchterAgo** [comment]
It might also have changed on their end. I mean at one point they did put "Altcoins" into their payment options and documentation. I find it unlikely that they would put this without checking it. Also, this particular entry was added in #301 and the author specifically states that he checked the BCH (CoinGate) integration is working.

I generally try to search for documentation of the payment options first. If there are none, I try to get presented with the payment options. If it is still unclear, I try to contact customer support. If all of those fail I do a purchase, sometimes I even actually buy a service/item.

**Comment by EchterAgo** [comment]
@nacardin maybe you can add some info here?
