### ISSUE TITLE
Add Satoshi Wallet to wallets.yml

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#98]
https://www.reddit.com/r/btc/comments/72cjiv/new_satoshi_bitcoin_cash_wallet_for_ios_android/

**Comment by kenman345** [comment]
anyone got a logo for this?

**Comment by kenman345** [comment]
Closing this issue until we can validate the validity and safety of using this wallet.

**Comment by rawb0t** [comment]
Agreed with needing to determine the validity and safety of using this wallet. The fact that it seems to work entirely through SMS is cause enough for alarm.

- Obvious privacy issues from needing your phone number
- Potential for it to be an SMS 2FA grab
- Even if they themselves aren't grabbing it for nefarious purposes, a database leak would likely be detrimental to users.
