### ISSUE TITLE
Add 'not yet to be named !' to the 'gold' category

### ISSUE THREAD

**Issue by accept-bitcoin-cash** [acceptbitcoincash/acceptbitcoincash#994]
Requesting to add 'not yet to be named !' to the 'gold' category. 

Details follow: 
```yml 
- name: not yet to be named !
      url: http://somewhere.org
      img: 
      bch: Yes
      btc: Yes
      othercrypto: Yes
      exceptions: 
        text: "Not enough funds to reply to the yours.org post about this:

@axelgembe  wrote:
"acceptbitcoin.cash could certainly use some help, be it from BitPay or from people with too much time like me, to find these vendors."

I almost submitted a merchant not listed,
 until I realized the form on your site was a direct submission,
as opposed to something to be followed up.

The firm in question may or may not wish to be listed,
and it would be (in this particular instance) highly rude of myself to presume he wished so,

What is very necessary on your site is both:
* a URL **recommendation** so that you can follow-up for approval before just linking.
* a URL **let's do this** submission for entities that probably are not shy

Bear in mind there are legal domains where simply getting put on such a list may get someone into legal quagmires that do not end well for those so listed.

Obviously, in the case of a street vendor or some storefront selling toys or whatnot, such consideration may not be necessary - be very careful with this.

For a merchant trading large transactions of valuables this may very well not be the case - they may prefer to remain off-grid due to reasons we may only guess at.

Again - recognize there exist governments that are **hunting down and imprisoning** people running businesses accepting anything that even resembles crypto of any sort."
```

Resources for adding this merchant:
[Link to not yet to be named !](http://somewhere.org)
Maybe you might want to check their Alexa Rank: [https://www.alexa.com/siteinfo/somewhere.org](https://www.alexa.com/siteinfo/somewhere.org)

- Verify site is legitimate and safe to list.
- Correct data in form if any is inaccurate.

If everything looks okay, Add it to the site:
- Assign to yourself when you begin work.
- Download and resize the image and put it into the proper img folder.
- Add listing alphabetically to proper .yml file.
- Commit changes mentioning this issue number with `closes #[ISSUE NUMBER HERE]`.

**Comment by joshmcintyre** [comment]
I'm not sure what this is trying to do, but there's no website to add here.

**Comment by EchterAgo** [comment]
This is a reply to a post of mine on yours.org. I basically said that we could use help finding merchants. The reply basically wants us to follow up with each merchant whether they want to be listed or not. I don't really know whether this is something we should do or not.
